# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9656ef8698bf13a34d903ac800f94e52fb13559db21debf866c5babb8ec377ec84bcff9e216186c52df9c49f6792148679208efc0057612b340eac4053496cbf

test:
  secret_key_base: c6c251ea2918058ba49703f1b451848c67f126590705f3fdbd835506941f2abd4a859bc328afe6143601c41de2af6e2157761ee9dcb6709a8466030b423a5f5a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
